dictInv =  {
    'um': 1,
    'dois': 2,
    'três': 3,
    'quatro': 4,
    'cinco': 5,
    'seis': 6,
    'sete': 7,
    'oito': 8,
    'nove': 9,

    # 'dez': 1,
    'vinte': 2,
    'trinta': 3,
    'quarenta': 4,
    'cinquenta': 5,
    'sessenta': 6,
    'setenta': 7,
    'oitenta': 8,
    'noventa': 9,

    'cem': 100,
    'cento': 1,
    'duzentos': 2,
    'trezentos': 3,
    'quatrocentos': 4,
    'quinhentos': 5,
    'seiscentos': 6,
    'setecentos': 7,
    'oitocentos': 8,
    'novecentos': 9,

    'dez': 10,
    'onze': 11,
    'doze': 12,
    'treze': 13,
    'quatorze': 14,
    'quinze': 15,
    'dezasseis': 16,
    'dezassete': 17,
    'dezoito': 18,
    'dezanove': 19,
}