import unicodedata

def removeAccents(string):
  return unicodedata.normalize('NFKD', string).encode('ASCII', 'ignore').decode('utf-8')

linguas = {
    'afrikaans' : 'af',
    'albanes' : 'sq',
    'arabe' : 'ar',
    'azerbaijano' : 'az',
    'basco' : 'eu',
    'bielorrusso' : 'be',
    'bengali' : 'bn',
    'bosnio' : 'bs',
    'bulgaro' : 'bg',
    'catalao' : 'ca',
    'cebuano' : 'ceb',
    'chines' : 'zh',
    'croata' : 'hr',
    'tcheco' : 'cs',
    'dinamarques' : 'da',
    'holandes' : 'nl',
    'ingles' : 'en',
    'esperanto' : 'eo',
    'estoniano' : 'et',
    'filipino' : 'tl',
    'finlandes' : 'fi',
    'frances' : 'fr',
    'galego' : 'gl',
    'georgiano' : 'ka',
    'alemao' : 'de',
    'grego' : 'el',
    'gujarati' : 'gu',
    'haitiano' : 'Creole ht',
    'hebraico' : 'iw',
    'hindi' : 'hi',
    'hmong' : 'hmn',
    'hungaro' : 'hu',
    'islandes' : 'is',
    'indonesio' : 'id',
    'irlandes' : 'ga',
    'italiano' : 'it',
    'japones' : 'ja',
    'javanes' : 'jw',
    'kannada' : 'kn',
    'khmer' : 'km',
    'coreano' : 'ko',
    'laos' : 'lo',
    'latim' : 'la',
    'letao' : 'lv',
    'lituano' : 'lt',
    'macedonio' : 'mk',
    'malaio' : 'ms',
    'maltes' : 'mt',
    'marata' : 'mr',
    'noruegues' : 'no',
    'persa' : 'fa',
    'polaco' : 'pl',
    'portugues' : 'pt',
    'romeno' : 'ro',
    'russo' : 'ru',
    'servio' : 'sr',
    'eslovaco' : 'sk',
    'esloveno' : 'sl',
    'espanhol' : 'es',
    'suaili' : 'sw',
    'sueco' : 'sv',
    'tamil' : 'ta',
    'telugu' : 'te',
    'tailandes' : 'th',
    'turco' : 'tr',
    'ucraniano' : 'uk',
    'urdu' : 'ur',
    'vietnamita' : 'vi',
    'gales' : 'cy',
    'iidiche' : 'yi'
}