adivinhas =[
"altos castelos verdes e amarelos::laranjeira",
"ave sou/penas nao tenho/pêlo de ovelha me cobre/de cabeça sou mui pobre/numa árvore me sustenho::avelã",
"branco é, galinha o põe::ovo",
"casinha branca sem porta nem tranca::ovo",
"qual é a coisa, qual é ela, que mal entra em casa, fica logo á janela::botão",
"qual é o animal que tem mais que três olhos e menos que quatro?::piolho",
"qual é o cúmulo do egoísmo::não digo",
"sou começo de virtude/e sou pecado mortal/meu nome pode escrever-se/sem consoante nem vogal::vírgula",
"sou macho no natural/o que até custa a querer/vou-me deitar a afogar/para femea me fazer::gelo",
"verde foi meu nascimento/e de luto me vesti/para dar a luz ao mundo/mil tormentos padeci::azeitona",
"No campo me criei metida entre verdes laços; quem mais chora por mim é quem me faz em pedaços::cebola",
"alto está, alto mora, todos o vêem, ninguém o adora::sino da torre",
"alto está, alto mora, ninguem o vê, todos o adoram::Deus",
"mil marinhinhos , mil marinhões dois para fitas e quatro chantões::boi",
"uma velhinha muito encorrilhadinha, com uma tranquinha no cu, 'arriu' passa é, advinha lá o que é?::uva passa",
"qual é coisa, qual é ela, capelinha branca, sem porta nem tranca? :: ovo",
"qual é coisa, qual é ela, é do tamanho de um melão,e cabe no ninho de um verdelhão?::Um novelo",
"qual é coisa, qual é ela, tem dentes e não come, e dá de comer a quem tem fome?::garfo",
"qual é coisa, qual é ela,quanto mais se mira, menos se vê?::sol",
"qual é coisa, qual é ela, que tem dentes e não come?::pente",
"qual é coisa, qual é ela, cai no chão fica amarela?::ovo",
"qual é coisa, qual é ela, que é grande antes de ser pequena?::vela",
"qual é coisa, qual é ela, que tem capa verde e o coração vermelho?::melancia",
"qual é coisa, qual é ela, preto como uma panela?::O carvão",
"o que é, o que é, redondo como um cesto, comprido como uma corda?::poço",
"o que é, o que é, capelinha vermelha, sem porta nem telha?::coração",
"tem orelhas de gato, e gato não é, tem focinho de gato, e gato não é, tem rabo de gato, e gato não é, quem é?:: gata",
"de que cor é o cavalo branco de Napoleão?::Branco",
"de que lado é a asa da chávena?::Do lado de fora",
"adivinhar, adivinhar, qual a primeira coisa que se faz ao acordar?::Abrir os olhos",
"Sou frio e também sou quente, sou fraco e também sou forte, nunca posso estar parado,vejam lá a minha sorte!::vento",
"Qual é o macho que tem duas fêmeas?::pato",
]